lib/cosmosodyssey_web/router.ex
defmodule CosmosodysseyWeb.Router do
  use CosmosodysseyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug :put_root_layout, {CosmosodysseyWeb.LayoutView, :root}
  end

  pipeline :browser_auth do
    plug Cosmosodyssey.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", CosmosodysseyWeb do
    pipe_through [:browser]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", CosmosodysseyWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
  end

  scope "/", CosmosodysseyWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/bookings", BookingController, only: [:new, :create, :index]
    get "/routes", RouteController, :index
    get "/search", SearchController, :search
  end

  # Other scopes may use custom stacks.
  # scope "/api", CosmosodysseyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CosmosodysseyWeb.Telemetry
    end
  end
end

lib/cosmosodyssey_web/views/layout_view.ex
defmodule CosmosodysseyWeb.LayoutView do
  use CosmosodysseyWeb, :view
end

lib/cosmosodyssey_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Cosmosodyssey</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="navigation">
      <section class="container full-height">
        <nav role="navigation" class="flex-box">
          <%= if Cosmosodyssey.Authentication.load_current_user(@conn) do %>
          <div class="nav-links">
            <%= link "Home", id: "home_button", to: Routes.page_path(@conn, :index)%>
            <%= link "Bookings", id: "booking_button", to: Routes.booking_path(@conn, :index)%>
            <!--span><%=Cosmosodyssey.Authentication.load_current_user(@conn).first_name%> <%=Cosmosodyssey.Authentication.load_current_user(@conn).last_name%></span-->
            <%= link "Logout", id: "logout_button", to: Routes.session_path(@conn, :delete, Cosmosodyssey.Authentication.load_current_user(@conn)), method: "delete"%>
          </div>
          <% end %>
          <h1 class="nav-title">Space Adventure Agency</h1>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
      <a href='https://www.freepik.com/vectors/technology'>Technology vector created by brgfx - www.freepik.com</a>
    </main>
  </body>
</html>