lib/cosmosodyssey_web/router.ex
defmodule CosmosodysseyWeb.Router do
  use CosmosodysseyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug :put_root_layout, {CosmosodysseyWeb.LayoutView, :root}
  end

  pipeline :browser_auth do
    plug Cosmosodyssey.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", CosmosodysseyWeb do
    pipe_through [:browser]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", CosmosodysseyWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
  end

  scope "/", CosmosodysseyWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/bookings", BookingController, only: [:new, :create, :index]
    get "/routes", RouteController, :index
    get "/search", SearchController, :search
  end

  # Other scopes may use custom stacks.
  # scope "/api", CosmosodysseyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CosmosodysseyWeb.Telemetry
    end
  end
end

lib/cosmosodyssey/data/route.ex
defmodule Cosmosodyssey.Data.Route do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :string, []}
  @derive {Phoenix.Param, key: :id}
  schema "routes" do
    field :dropoff_planet, :string
    field :pickup_planet, :string
    field :distance, :integer
    has_many :providers, Cosmosodyssey.Data.Provider
    belongs_to :price_list, Cosmosodyssey.Data.PriceList, type: :string
    timestamps()
  end

  def changeset(route, attrs) do
    route
    |> cast(attrs, [:id, :dropoff_planet, :pickup_planet, :distance])
    |> validate_required([:id, :dropoff_planet, :pickup_planet, :distance])
    |> validate_number(:distance, greater_than: -1)
    |> unique_constraint(:id)
  end
end

lib/cosmosodyssey_web/controllers/route_controller.ex
defmodule CosmosodysseyWeb.RouteController do
  use CosmosodysseyWeb, :controller

  alias Cosmosodyssey.Repo
  alias Cosmosodyssey.Data.Provider
  alias CosmosodysseyWeb.SearchController

  defp filter_providers(route_and_providers, company) do
    # filter providers by company
    route_and_providers |> Enum.map(fn {from_to, providers} ->
      {from_to, Enum.filter(providers, fn provider -> provider.provider.company == company end)}
    end)
  end

  defp order_providers(route_and_providers, params) do
    # order providers by a field and either in desc or asc order
    {type, field} = order_by(params)
    if type == nil || field == nil do
      route_and_providers
    end
    case field == :time do
      true ->
        route_and_providers |> Enum.map(fn {from_to, providers} ->
          {from_to, Enum.sort_by(providers, &(&1.duration), type)}
        end)
      false ->
        route_and_providers |> Enum.map(fn {from_to, providers} ->
          {from_to, Enum.sort_by(providers, &(Map.get &1.provider, field), type)}
        end)
    end
  end

  defp order_by("price_asc"), do: {:asc, :price}
  defp order_by("price_desc"), do: {:desc, :price}
  defp order_by("distance_asc"), do: {:asc, :distance}
  defp order_by("distance_desc"), do: {:desc, :distance}
  defp order_by("travel_time_desc"), do: {:desc, :time}
  defp order_by("travel_time_asc"), do: {:asc, :time}
  defp order_by(_), do: {nil, nil}

  defp get_sorted_indexes(ids) do
    # all params have indexes to know their order, but these indexes must be subtracted out of the param
    id_indexes = ids |> Enum.map(fn{param_name, id} ->
      # the param is in the form "booking_opt_#", where we only need the last # as an integer
      {idx_int, _} = Integer.parse(List.last(String.split(param_name, "_")))
      {idx_int, id}
    end)
    # sort the indexes to know in which order the providers are in according to the route
    id_indexes |> List.keysort(0)
  end

  defp get_chronological_validity(sorted) do
    # check if all providers are chronologically in order
    provider_pairs = sorted |> Enum.map(fn{_, id} ->
      Repo.get!(Provider, id)
    end) |> Enum.chunk_every(2, 1, :discard) # chunk them in groups of 2 so we can compare their end and start times
    provider_pairs |> Enum.map(fn [provider1, provider2]->
      {:ok, parsed_end_time} = SearchController.string_to_datetime(provider1.end_time)
      {:ok, parsed_start_time} = SearchController.string_to_datetime(provider2.start_time)
      Timex.before?(parsed_end_time, parsed_start_time)
    end)
  end

  def index(conn, %{"from" => from, "to" => to}) do
    # function for resetting the filter selections
    case SearchController.get_valid_price_list() do
      {:ok, pl} ->
        {providers, pairs} = SearchController.get_providers(pl.id, from, to)
        render(conn, "index.html", providers: providers, routes: pairs, pickup_planet: from, dropoff_planet: to)
      {:error, nil} -> conn
                       |> put_flash(:error, "Price list expired during booking process. Please search again!")
                       |> redirect(to: Routes.page_path(conn, :index))
      end
  end

  def index(conn, %{"book" => params}) do
    # on booking button click, sends selected options to booking controller
    # get all passed parameters
    from = get_in(params, ["from"])
    to = get_in(params, ["to"])
    route_no = get_in(params, ["route_no"])
    # filter out provider ID-s from the params
    ids = params |> Enum.filter(fn {param_name, _} ->
      String.starts_with?(param_name, "booking_opt_")
    end)
    {route_no_int, _} = Integer.parse(route_no)
    # check that the required number of providers was selected in order to make booking
    case route_no_int == length(ids) do
      false ->
        case SearchController.get_valid_price_list() do
          {:ok, pl} ->
            {providers, pairs} = SearchController.get_providers(pl.id, from, to)
            conn
            |> put_flash(:error, "Please choose a trip in all subroutes!")
            |> render("index.html", providers: providers, routes: pairs, pickup_planet: from, dropoff_planet: to)
          {:error, nil} -> conn
                           |> put_flash(:error, "Price list expired during booking process. Please search again!")
                           |> redirect(to: Routes.page_path(conn, :index))
        end
      true ->
        # get sorted indexes, then get providers in the correct order with those indexes
        sorted = get_sorted_indexes(ids)
        # check if the selected trips are in chronological order
        is_valid = get_chronological_validity(sorted)
        case SearchController.get_valid_price_list() do
          {:ok, pl} ->
            {providers, pairs} = SearchController.get_providers(pl.id, from, to)
            # if there is a false in is_valid, then there exists dates that are in incorrect order
            case Enum.member?(is_valid, false) do
              true ->
                conn
                |> put_flash(:error, "Please choose trips that are in chronological order!")
                |> render("index.html", providers: providers, routes: pairs, pickup_planet: from, dropoff_planet: to)
              false ->
                # Phoenix does not allow to pass complex maps or lists as params, so extract the ids as a simple list
                ids = sorted |> Enum.map(fn {_, id} -> id end)
                conn
                |> redirect(to: Routes.booking_path(conn, :new, providers: ids, routes: pairs, from: from, to: to))
            end
          {:error, nil} ->
            conn
             |> put_flash(:error, "Price list expired during booking process. Please search again!")
             |> redirect(to: Routes.page_path(conn, :index))
        end
    end
  end

  def index(conn, %{"filter" => filter_params, "order_by" => order_by}) do
    # on filter button click, sends selected filtered/ordered providers to template
    # extract params
    company = get_in(filter_params, ["company"])
    from = get_in(filter_params, ["from"])
    to = get_in(filter_params, ["to"])
    case SearchController.get_valid_price_list() do
      {:error, nil} -> conn
                       |> put_flash(:error, "Price list expired during booking process. Please search again!")
                       |> redirect(to: Routes.page_path(conn, :index))
      {:ok, pl} ->
        {providers, pairs} = SearchController.get_providers(pl.id, from, to)
        # check all cases (and act accordingly):
        #   if filter exists and order_by not
        #   if filter exists and order_by as well
        #   if filter doesn't exist and order_by does
        #   if neither filter or order_by exist
        case company != nil && company != "" do
          true ->
            filtered = filter_providers(providers, company)
            case order_by != nil && order_by != "" do
              true ->
                ordered = order_providers(filtered, order_by)
                render(conn, "index.html", providers: ordered, routes: pairs, pickup_planet: from, dropoff_planet: to)
              false ->
                render(conn, "index.html", providers: filtered, routes: pairs, pickup_planet: from, dropoff_planet: to)
            end
          false ->
            case order_by != nil && order_by != "" do
              true ->
                ordered = order_providers(providers, order_by)
                render(conn, "index.html", providers: ordered, routes: pairs, pickup_planet: from, dropoff_planet: to)
              false ->
                render(conn, "index.html", providers: providers, routes: pairs, pickup_planet: from, dropoff_planet: to)
            end
        end
    end
  end
end

lib/cosmosodyssey_web/views/route_view.ex
defmodule CosmosodysseyWeb.RouteView do
  use CosmosodysseyWeb, :view
end

lib/cosmosodyssey_web/templates/route/index.html.eex
<h2>Book a trip</h2><h4>The chosen trips are the shortest possible route between your selected planets <%=@pickup_planet%> and <%=@dropoff_planet%>. Please select a suitable trip from each subroute.</h4>
<section class="results">
    <%= form_for @conn, Routes.route_path(@conn, :index), [method: :get, as: :book], fn b -> %>
        <%= for {{[from, to], provider_group}, outside_idx} <- Enum.with_index(@providers) do %>
        <h3>From <span class="planet"><%=from%></span> to <span class="planet"><%=to%></span></h3>
        <table class="table">
            <thead>
            <tr>
                <th>Company</th>
                <th>Start time</th>
                <th>End time</th>
                <th>Price</th>
                <th>Distance (km)</th>
                <th>Duration</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <%= for {provider, idx} <- Enum.with_index(provider_group) do %>
            <tr>
                <td><%= provider.provider.company %></td>
                <td><%= CosmosodysseyWeb.BookingController.format_single_datetime(provider.provider.start_time)%></td>
                <td><%= CosmosodysseyWeb.BookingController.format_single_datetime(provider.provider.end_time)%></td>
                <td><%= provider.provider.price %></td>
                <td><%= provider.distance %></td>
                <%= if provider.duration == 1 do%>
                <td><%= provider.duration %> day</td>
                <% end %>
                <%= if provider.duration != 1 do%>
                <td><%= provider.duration %> days</td>
                <% end %>
                <td class="text-right last-column">
                    <%= if length(@providers) == 1 do %>
                        <span><%= link "Book", id: "booking_button_#{idx}",
                        to: Routes.booking_path(@conn, :new, provider: provider.provider.id, from: @pickup_planet , to: @dropoff_planet, time: provider.duration) %></span>
                    <% end %>
                    <%= if length(@providers) > 1 do %>
                        <%= radio_button b, "booking_opt_#{outside_idx}", provider.provider.id, class: "form-control"  %>
                    <% end %>
                </td>
            </tr>
            <% end %>
            </tbody>
        </table>
        <% end %>
        <%= hidden_input b, :from, value: @pickup_planet %>
        <%= hidden_input b, :to, value: @dropoff_planet %>
        <%= hidden_input b, :route_no, value: length(@providers) %>
        <%= if length(@providers) > 1 do %>
            <%= submit "Book"%>
        <% end %>
    <% end %>
</section>
<section class="filter">
    <%= form_for @conn, Routes.route_path(@conn, :index), [method: :get, as: :filter], fn f -> %>
        <%= hidden_input f, :from, value: @pickup_planet, class: "form-control" %>
        <%= hidden_input f, :to, value: @dropoff_planet, class: "form-control" %>

        <%= label f, :company, "Filter by company" %>
        <%= text_input f, :company, id: "company", placeholder: "Company", class: "form-control"%>
        <%= label f, :order_by, "Order by" %>
        <select name="order_by">
            <%= for {k, v} <- ["Order by": "", "Price": "price_asc", "Price (Desc)": "price_desc",
                "Distance": "distance_asc", "Distance (Desc)": "distance_desc",
                "Travel time": "travel_time_asc", "Travel time (Desc)": "travel_time_desc",] do %>
            <option value="<%= v %>"> <%= k %>
            <% end %>
        </select>
        <%= submit "Filter"%> <%= link "Clear", id: "clear_button", to: Routes.route_path(@conn, :index, from: @pickup_planet, to: @dropoff_planet)%>
    <% end %>
</section>